services:
  db:
    image: postgres:16
    container_name: mini_task_db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_pass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks_user -d tasks"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  dbdata:
