services:
  db:
    image: postgres:16
    container_name: mini_task_db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_pass
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks_user -d tasks"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: mini_task_api
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8080

      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: tasks_user
      DB_PASS: tasks_pass

      JWT_SECRET: change-me-in-prod-use-long-secret
      JWT_TTL_MINUTES: 60
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: mini_task_web
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  dbdata:
